# Generated by Django 2.0.8 on 2018-08-28 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(max_length=200, verbose_name='custom_name')),
                ('custom_dept', models.CharField(max_length=200, verbose_name='custom_dept')),
            ],
            options={
                'verbose_name': 'Custom',
                'verbose_name_plural': 'Custom',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_id', models.CharField(max_length=200, verbose_name='proj_id')),
                ('proj_name', models.CharField(max_length=200, verbose_name='proj_name')),
                ('platform', models.CharField(choices=[('pb', 'Pacbio'), ('ont', 'Nanopore'), ('bionano', 'Bionano'), ('ngs', 'NGS')], default='ont', max_length=20, verbose_name='platform')),
                ('analysis_type', models.CharField(choices=[('met', '甲基化'), ('sv', '结构变异'), ('str', '串联重复'), ('tumor', '肿瘤'), ('haplotype', '单体型')], default='sv', max_length=20, verbose_name='analysis_type')),
                ('start', models.DateField(blank=True, null=True, verbose_name='start')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='deadline')),
                ('state', models.CharField(choices=[('to-do', 'To Do'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('done', 'Done'), ('dismissed', 'Dismissed')], default='to-do', max_length=20, verbose_name='state')),
                ('priority', models.CharField(choices=[('00_low', 'Low'), ('10_normal', 'Normal'), ('20_high', 'High'), ('30_critical', 'Critical'), ('40_blocker', 'Blocker')], default='10_normal', max_length=20, verbose_name='priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='description')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('custom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_custom', to='pm.Custom')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_assigned', to=settings.AUTH_USER_MODEL, verbose_name='销售')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=200, verbose_name='sample_id')),
                ('sample_name', models.CharField(max_length=200, verbose_name='sample_name')),
                ('platform', models.CharField(choices=[('pb', 'Pacbio'), ('ont', 'Nanopore'), ('bionano', 'Bionano'), ('ngs', 'NGS')], default='ont', max_length=20, verbose_name='platform')),
                ('analysis_type', models.CharField(choices=[('met', '甲基化'), ('sv', '结构变异'), ('str', '串联重复'), ('tumor', '肿瘤'), ('haplotype', '单体型')], default='sv', max_length=20, verbose_name='analysis_type')),
                ('start', models.DateField(blank=True, null=True, verbose_name='start')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='deadline')),
                ('priority', models.CharField(choices=[('00_low', 'Low'), ('10_normal', 'Normal'), ('20_high', 'High'), ('30_critical', 'Critical'), ('40_blocker', 'Blocker')], default='10_normal', max_length=20, verbose_name='priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('state', models.CharField(choices=[('to-do', 'To Do'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('done', 'Done'), ('dismissed', 'Dismissed')], default='to-do', max_length=20, verbose_name='state')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'Sample',
                'verbose_name_plural': 'Sample',
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jianku_date', models.DateTimeField(verbose_name='jianku_date')),
                ('sample_type', models.CharField(choices=[('dna', 'DNA'), ('rna', 'RNA')], default='dna', max_length=20, verbose_name='sample_type')),
                ('library_id', models.CharField(max_length=200, verbose_name='library_id')),
                ('machine_id', models.CharField(choices=[('G01', 'GridION_1'), ('G02', 'GridION_2'), ('G03', 'GridION_3'), ('G04', 'GridION_4'), ('P01', 'PromethION_1')], max_length=200, verbose_name='machine_id')),
                ('cell_id', models.CharField(max_length=200, verbose_name='cell_id')),
                ('sequence_time', models.DateTimeField(verbose_name='sequence_time')),
                ('yield_data', models.FloatField(verbose_name='yield_data')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequence_user', to=settings.AUTH_USER_MODEL, verbose_name='测序人员')),
            ],
            options={
                'verbose_name': 'Sequence',
                'verbose_name_plural': 'Sequence',
            },
        ),
    ]
