# Generated by Django 2.0.8 on 2018-08-29 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='姓名')),
                ('dept', models.CharField(max_length=200, verbose_name='区域')),
                ('tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
            ],
            options={
                'verbose_name': '销售列表',
                'verbose_name_plural': '销售',
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AddField(
            model_name='custom',
            name='tel',
            field=models.CharField(default='-', max_length=20, verbose_name='客户电话'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custom',
            name='custom_dept',
            field=models.CharField(max_length=200, verbose_name='客户单位'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='custom_name',
            field=models.CharField(max_length=200, verbose_name='客户名称'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='analysis_type',
            field=models.CharField(choices=[('met', '甲基化'), ('sv', '结构变异'), ('str', '串联重复'), ('tumor', '肿瘤'), ('haplotype', '单体型')], default='sv', max_length=20, verbose_name='分析类型'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='截止时间'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='上次修改'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='platform',
            field=models.CharField(choices=[('pb', 'Pacbio'), ('ont', 'Nanopore'), ('bionano', 'Bionano'), ('ngs', 'NGS')], default='ont', max_length=20, verbose_name='测序平台'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='priority',
            field=models.CharField(choices=[('00_low', 'Low'), ('10_normal', 'Normal'), ('20_high', 'High'), ('30_critical', 'Critical'), ('40_blocker', 'Blocker')], default='10_normal', max_length=20, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_id',
            field=models.CharField(max_length=200, verbose_name='样本编号'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_name',
            field=models.CharField(max_length=200, verbose_name='样本姓名'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='state',
            field=models.CharField(choices=[('weishouyang', '未收样'), ('shouyang', '收样'), ('tiqu', '提取'), ('jianku', '建库'), ('shangji', '上机测序'), ('fenxi', '生信分析'), ('jiedu', '报告解读'), ('jiaofu', '交付')], default='to-do', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='project',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='pm.Sale', verbose_name='销售'),
        ),
    ]
