# Generated by Django 2.0.8 on 2018-08-29 09:38

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0002_auto_20180829_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分析类型')),
            ],
            options={
                'verbose_name': 'Custom',
                'verbose_name_plural': 'Custom',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='analysis_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('met', '甲基化'), ('sv', '结构变异'), ('str', '串联重复'), ('tumor', '肿瘤'), ('haplotype', '单体型')], default='sv', max_length=20, verbose_name='analysis_type'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='analysis_type',
            field=models.CharField(choices=[('Met', '甲基化'), ('SV', '结构变异'), ('STR', '串联重复'), ('Tumor', '肿瘤'), ('Haplotype', '单体型')], default='sv', max_length=20, verbose_name='分析类型'),
        ),
    ]
