# Generated by Django 2.0.8 on 2018-08-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0003_auto_20180829_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis_type',
            options={'verbose_name': '分析类型', 'verbose_name_plural': '分析类型'},
        ),
    ]
