# Generated by Django 2.0.8 on 2018-08-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0005_auto_20180829_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='tel',
            field=models.CharField(blank=True, max_length=20, verbose_name='客户电话'),
        ),
    ]
