# Generated by Django 2.0.8 on 2018-08-29 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0006_auto_20180829_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='sequence_time',
        ),
        migrations.AddField(
            model_name='sample',
            name='cexu_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上机开始时间'),
        ),
        migrations.AddField(
            model_name='sample',
            name='jianku_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='建库开始时间'),
        ),
        migrations.AddField(
            model_name='sample',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample', to='pm.Project', verbose_name='合同编号'),
        ),
        migrations.AddField(
            model_name='sample',
            name='shengxin_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生信开始时间'),
        ),
        migrations.AddField(
            model_name='sample',
            name='tiqu_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提取开始时间'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequence', to='pm.Sample', verbose_name='样本编号'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='sequence_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sequence_end'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='sequence_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sequence_start'),
        ),
    ]
