# Generated by Django 2.0.8 on 2018-08-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0009_auto_20180829_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='cell_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='cell_id'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='jianku_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='jianku_date'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='library_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='library_id'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='machine_id',
            field=models.CharField(blank=True, choices=[('G01', 'GridION_1'), ('G02', 'GridION_2'), ('G03', 'GridION_3'), ('G04', 'GridION_4'), ('P01', 'PromethION_1')], max_length=200, null=True, verbose_name='machine_id'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='sample_type',
            field=models.CharField(blank=True, choices=[('dna', 'DNA'), ('rna', 'RNA')], default='dna', max_length=20, null=True, verbose_name='sample_type'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='yield_data',
            field=models.FloatField(blank=True, null=True, verbose_name='yield_data'),
        ),
    ]
