# Generated by Django 2.0.8 on 2018-08-30 03:59

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0010_auto_20180829_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='机器编号')),
                ('platform', models.CharField(max_length=200, verbose_name='平台')),
                ('dept', models.CharField(blank=True, max_length=200, null=True, verbose_name='部门')),
            ],
            options={
                'verbose_name': '测序仪',
                'verbose_name_plural': '测序仪',
            },
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'verbose_name': '样本', 'verbose_name_plural': '样本'},
        ),
        migrations.AlterField(
            model_name='project',
            name='analysis_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('甲基化', '甲基化'), ('结构变异', '结构变异'), ('肿瘤', '肿瘤')], default='sv', max_length=20, verbose_name='分析类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='custom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_custom', to='pm.Custom', verbose_name='客户名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='截止日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='platform',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Pacbio', 'Pacbio'), ('Nanopore', 'Nanopore'), ('Bionano', 'Bionano'), ('NGS', 'NGS')], default='ont', max_length=20, verbose_name='测序平台'),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('00_low', 'Low'), ('10_normal', 'Normal'), ('20_high', 'High'), ('30_critical', 'Critical'), ('40_blocker', 'Blocker')], default='10_normal', max_length=20, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_id',
            field=models.CharField(max_length=200, verbose_name='合同号'),
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_name',
            field=models.CharField(max_length=200, verbose_name='合同名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='启动时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('to-do', 'To Do'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('done', 'Done'), ('dismissed', 'Dismissed')], default='to-do', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='platform',
            field=models.CharField(choices=[('Pacbio', 'Pacbio'), ('Nanopore', 'Nanopore'), ('Bionano', 'Bionano'), ('NGS', 'NGS')], default='ont', max_length=20, verbose_name='测序平台'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='jianku_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='prep_time'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='sample_type',
            field=models.CharField(blank=True, choices=[('DNA', 'DNA'), ('RNA', 'RNA')], default='dna', max_length=20, null=True, verbose_name='sample_type'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='yield_data',
            field=models.IntegerField(blank=True, null=True, verbose_name='Active Pore G4'),
        ),
    ]
