# Generated by Django 2.0.8 on 2018-08-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0011_auto_20180830_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='ap_g1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Active Pore G1'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='ap_g2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Active Pore G2'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='ap_g3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Active Pore G3'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='ap_g4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Active Pore G4'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='ap_muxscan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Muxscan'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='ap_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='machine_id',
            field=models.CharField(blank=True, choices=[('PromethION', 'PromethION')], max_length=200, null=True, verbose_name='machine_id'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='yield_data',
            field=models.FloatField(blank=True, null=True, verbose_name='yield_data'),
        ),
    ]
