# Generated by Django 2.0.8 on 2018-08-30 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0012_auto_20180830_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='project',
            name='custom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_custom', to='pm.Custom', verbose_name='客户名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project', to='pm.Sale', verbose_name='销售'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sample_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sample', to='pm.Project', verbose_name='合同编号'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sequence_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sequence', to='pm.Sample', verbose_name='样本编号'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sequence_user', to=settings.AUTH_USER_MODEL, verbose_name='测序人员'),
        ),
    ]
