# Generated by Django 2.0.8 on 2018-08-30 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pm', '0013_auto_20180830_0523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bioinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bases', models.BigIntegerField(verbose_name='原始数据量')),
                ('total_reads', models.PositiveIntegerField(verbose_name='原始reads数目')),
                ('pass_bases', models.BigIntegerField(verbose_name='过滤数据量')),
                ('pass_total_reads', models.PositiveIntegerField(verbose_name='过滤reads数目')),
                ('pass_reads_avg', models.PositiveIntegerField(verbose_name='Reads平均长度')),
                ('pass_reads_n50', models.PositiveIntegerField(verbose_name='Reads N50长度')),
                ('pass_reads_median', models.PositiveIntegerField(verbose_name='Reads中位数长度')),
                ('pass_reads_avg_score', models.PositiveSmallIntegerField(verbose_name='平均质量值')),
                ('mapped_reads', models.PositiveIntegerField(verbose_name='过滤reads数目')),
                ('mapped_bases', models.BigIntegerField(verbose_name='过滤数据量')),
                ('error_rate', models.FloatField(blank=True, null=True, verbose_name='yield_data')),
                ('re', models.IntegerField(blank=True, null=True, verbose_name='DEL数目')),
                ('del_amount', models.IntegerField(blank=True, null=True, verbose_name='DEL数目')),
                ('ins_amount', models.IntegerField(blank=True, null=True, verbose_name='INS数目')),
                ('inv_amount', models.IntegerField(blank=True, null=True, verbose_name='INV数目')),
                ('dup_amount', models.IntegerField(blank=True, null=True, verbose_name='DUP数目')),
                ('tra_amount', models.IntegerField(blank=True, null=True, verbose_name='TRA数目')),
                ('bioinfo_start', models.DateTimeField(blank=True, null=True, verbose_name='生信分析开始时间')),
                ('bioinfo_end', models.DateTimeField(blank=True, null=True, verbose_name='生信分析结束时间')),
                ('report_end', models.DateTimeField(blank=True, null=True, verbose_name='报告解读结束时间')),
                ('raw_dir', models.CharField(blank=True, max_length=200, null=True, verbose_name='Raw data 路径')),
                ('pass_dir', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pass data 路径')),
                ('analysis_dir', models.CharField(blank=True, max_length=200, null=True, verbose_name='分析目录')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='上次修改')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bioinfo_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': '生信分析',
                'verbose_name_plural': '生信分析',
            },
        ),
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='下单编号')),
                ('order_date', models.DateTimeField(blank=True, null=True, verbose_name='下单时间')),
                ('proj_type', models.CharField(blank=True, choices=[('科研', '科研'), ('临床', '临床')], max_length=50, null=True, verbose_name='项目类型')),
                ('bct_id', models.CharField(blank=True, choices=[('科研', '科研'), ('临床', '临床')], max_length=500, null=True, verbose_name='采血管编号')),
                ('bct_amount', models.IntegerField(blank=True, null=True, verbose_name='管数')),
                ('sample_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='样本类型')),
                ('method', models.CharField(blank=True, max_length=20, null=True, verbose_name='提取方法')),
                ('is_finish', models.BooleanField(default=False, verbose_name='是否完成')),
                ('finish_date', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='上次修改')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extract_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': '上机测序',
                'verbose_name_plural': '上机测序',
            },
        ),
        migrations.AlterModelOptions(
            name='custom',
            options={'verbose_name': '客户', 'verbose_name_plural': '客户'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelOptions(
            name='sequence',
            options={'verbose_name': '上机测序', 'verbose_name_plural': '上机测序'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='state',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='cexu_start',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='jianku_start',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='shengxin_start',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='state',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='tiqu_start',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='cell_id',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='jianku_date',
        ),
        migrations.AddField(
            model_name='custom',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='国家'),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='合同分类'),
        ),
        migrations.AddField(
            model_name='project',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='票号'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_invoice',
            field=models.BooleanField(default=False, verbose_name='是否开票'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_pay',
            field=models.BooleanField(default=False, verbose_name='是否收款'),
        ),
        migrations.AddField(
            model_name='project',
            name='pay_money',
            field=models.IntegerField(blank=True, null=True, verbose_name='已付款'),
        ),
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='总额'),
        ),
        migrations.AddField(
            model_name='project',
            name='proj_owner',
            field=models.CharField(choices=[('北京希望组', '北京希望组'), ('武汉希望组', '武汉希望组'), ('武汉未来组', '武汉未来组')], default='北京希望组', max_length=200, verbose_name='项目归属'),
        ),
        migrations.AddField(
            model_name='project',
            name='sample_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='样本数目'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Blocked', 'Blocked'), ('Done', 'Done'), ('Dismissed', 'Dismissed')], default='to-do', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='sample',
            name='bioinfo_finish',
            field=models.BooleanField(default=False, verbose_name='生信完成'),
        ),
        migrations.AddField(
            model_name='sample',
            name='data_zize',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='数据量'),
        ),
        migrations.AddField(
            model_name='sample',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='交付时间'),
        ),
        migrations.AddField(
            model_name='sample',
            name='extract_finish',
            field=models.BooleanField(default=False, verbose_name='提取完成'),
        ),
        migrations.AddField(
            model_name='sample',
            name='library_finish',
            field=models.BooleanField(default=False, verbose_name='建库完成'),
        ),
        migrations.AddField(
            model_name='sample',
            name='receive_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='收样开始时间'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_name2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='修正姓名'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='样本类型'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sequence_finish',
            field=models.BooleanField(default=False, verbose_name='测序完成'),
        ),
        migrations.AddField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('未收样', '未收样'), ('收样', '收样'), ('提取', '提取'), ('建库', '建库'), ('上机测序', '上机测序'), ('生信分析', '生信分析'), ('报告解读', '报告解读'), ('交付', '交付')], default='to-do', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='cell_pos',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='上机位置'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='library_require',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='建库要求'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='library_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='建库时间'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下单时间'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='order_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='下单编号'),
        ),
        migrations.AlterField(
            model_name='project',
            name='analysis_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('甲基化', '甲基化'), ('结构变异', '结构变异'), ('肿瘤', '肿瘤')], max_length=20, verbose_name='分析类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('Hign', 'High'), ('Critical', 'Critical'), ('Blocker', 'Blocker')], default='10_normal', max_length=20, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='analysis_type',
            field=models.CharField(blank=True, choices=[('Met', '甲基化'), ('SV', '结构变异'), ('STR', '串联重复'), ('Tumor', '肿瘤'), ('Haplotype', '单体型')], max_length=20, null=True, verbose_name='分析类型'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='platform',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Pacbio', 'Pacbio'), ('Nanopore', 'Nanopore'), ('Bionano', 'Bionano'), ('NGS', 'NGS')], max_length=20, null=True, verbose_name='测序平台'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('Hign', 'High'), ('Critical', 'Critical'), ('Blocker', 'Blocker')], default='10_normal', max_length=20, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sequence_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='library_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='文库编号'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='machine_id',
            field=models.CharField(blank=True, choices=[('PromethION', 'PromethION')], max_length=50, null=True, verbose_name='机器编号'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='sample_type',
            field=models.CharField(blank=True, choices=[('DNA', 'DNA'), ('RNA', 'RNA')], default='DNA', max_length=20, null=True, verbose_name='样本类型'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='sequence_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='测序结束时间'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='sequence_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='测序开始时间'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sequence', to=settings.AUTH_USER_MODEL, verbose_name='测序人员'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='yield_data',
            field=models.FloatField(blank=True, null=True, verbose_name='产量'),
        ),
        migrations.AddField(
            model_name='extraction',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extract', to='pm.Sample', verbose_name='样本编号'),
        ),
        migrations.AddField(
            model_name='bioinfo',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Bioinfo', to='pm.Sample', verbose_name='样本编号'),
        ),
        migrations.AddField(
            model_name='bioinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bioinfo', to=settings.AUTH_USER_MODEL, verbose_name='分析人员'),
        ),
    ]
