# Generated by Django 2.0.8 on 2018-08-30 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0014_auto_20180830_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extraction',
            options={'verbose_name': '提取', 'verbose_name_plural': '提取'},
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='data_zize',
            new_name='data_size',
        ),
    ]
