# Generated by Django 2.0.8 on 2018-09-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0015_auto_20180830_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_short', models.CharField(max_length=200, verbose_name='平台名称')),
                ('name_long', models.CharField(max_length=200, verbose_name='平台名称2')),
            ],
            options={
                'verbose_name': '测序平台',
                'verbose_name_plural': '测序平台',
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='analysis_type',
        ),
        migrations.AddField(
            model_name='project',
            name='analysis_type',
            field=models.ManyToManyField(blank=True, to='pm.Analysis_Type', verbose_name='分析类型'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='platform',
        ),
        migrations.AddField(
            model_name='project',
            name='platform',
            field=models.ManyToManyField(blank=True, to='pm.Platform', verbose_name='测序平台'),
        ),
    ]
