# Generated by Django 2.0.8 on 2018-09-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0016_auto_20180902_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom',
            old_name='custom_dept',
            new_name='dept',
        ),
        migrations.RenameField(
            model_name='custom',
            old_name='custom_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='platform',
            old_name='name_short',
            new_name='name',
        ),
        migrations.AddField(
            model_name='custom',
            name='addr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='地址'),
        ),
    ]
