# Generated by Django 2.0.8 on 2018-09-02 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0017_auto_20180902_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machine', to='pm.Platform', verbose_name='测序平台'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name_long',
            field=models.CharField(max_length=200, verbose_name='平台全称'),
        ),
        migrations.RemoveField(
            model_name='sample',
            name='analysis_type',
        ),
        migrations.AddField(
            model_name='sample',
            name='analysis_type',
            field=models.ManyToManyField(blank=True, to='pm.Analysis_Type', verbose_name='分析类型'),
        ),
        migrations.RemoveField(
            model_name='sample',
            name='platform',
        ),
        migrations.AddField(
            model_name='sample',
            name='platform',
            field=models.ManyToManyField(blank=True, to='pm.Platform', verbose_name='测序平台'),
        ),
    ]
