# Generated by Django 2.0.8 on 2018-09-02 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0018_auto_20180902_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='machine_id',
        ),
        migrations.AddField(
            model_name='sequence',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sequence', to='pm.Machine', verbose_name='机器编号'),
        ),
    ]
