# Generated by Django 2.0.8 on 2018-09-02 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pm', '0019_auto_20180902_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extraction', to=settings.AUTH_USER_MODEL, verbose_name='提取人员'),
        ),
        migrations.AlterField(
            model_name='extraction',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='下单时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sequence',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='下单时间'),
            preserve_default=False,
        ),
    ]
