# Generated by Django 2.0.8 on 2018-09-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0020_auto_20180902_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='library_id',
            field=models.CharField(max_length=50, null=True, verbose_name='文库编号'),
        ),
    ]
