# Generated by Django 2.0.8 on 2018-09-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0022_auto_20180902_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='keshi',
            field=models.CharField(default=None, max_length=200, verbose_name='客户科室'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='修正姓名'),
        ),
        migrations.AddField(
            model_name='sample',
            name='clin_info',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='临床信息'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', '女'), ('M', '男'), ('U', '未知')], max_length=10, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='name',
            field=models.CharField(max_length=200, verbose_name='客户姓名'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='library_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='文库编号'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='library_kit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='建库试剂盒'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='library_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='建库大小'),
        ),
    ]
