# Generated by Django 2.0.8 on 2018-09-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0023_auto_20180918_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='dept',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='客户单位'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='keshi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='客户科室'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='客户姓名'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='客户电话'),
        ),
    ]
