# Generated by Django 2.0.8 on 2018-09-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0024_auto_20180918_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='dept',
        ),
        migrations.AddField(
            model_name='project',
            name='contract_id',
            field=models.CharField(default=None, max_length=200, verbose_name='合同编号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_id',
            field=models.CharField(max_length=200, verbose_name='项目编号'),
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='合同名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_owner',
            field=models.CharField(choices=[('北京希望组', '北京希望组'), ('武汉希望组', '武汉希望组'), ('武汉未来组', '武汉未来组')], default='北京希望组', max_length=200, null=True, verbose_name='项目归属'),
        ),
    ]
