# Generated by Django 2.0.8 on 2018-09-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0025_auto_20180918_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='合同编号'),
        ),
    ]
